name: game_do_vui
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  firebase_app_check: ^0.3.1+4
  badges: ^3.1.2
  flutter_launcher_icons: ^0.14.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  awesome_dialog: ^3.2.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo3.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/logo3.png
  #   - images/a_dot_ham.jpeg
