// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTvX4IHYdxVcI1u2V_5m-lHSqaE4R7-vY',
    appId: '1:247885656080:web:cc411386e3a7b0efad1a95',
    messagingSenderId: '247885656080',
    projectId: 'doan-9657f',
    authDomain: 'doan-9657f.firebaseapp.com',
    storageBucket: 'doan-9657f.appspot.com',
    measurementId: 'G-L09H98JVFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6tzigYihcfE5o4kFDqq-nO6XMZHbZX8',
    appId: '1:247885656080:android:93ab2521742c7bc4ad1a95',
    messagingSenderId: '247885656080',
    projectId: 'doan-9657f',
    storageBucket: 'doan-9657f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb8cSmrX-DQPFXVPi8vAL2NU-OJ8CMV4c',
    appId: '1:247885656080:ios:a3b2b33f4da60b95ad1a95',
    messagingSenderId: '247885656080',
    projectId: 'doan-9657f',
    storageBucket: 'doan-9657f.appspot.com',
    iosBundleId: 'com.example.shoppingTop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb8cSmrX-DQPFXVPi8vAL2NU-OJ8CMV4c',
    appId: '1:247885656080:ios:a3b2b33f4da60b95ad1a95',
    messagingSenderId: '247885656080',
    projectId: 'doan-9657f',
    storageBucket: 'doan-9657f.appspot.com',
    iosBundleId: 'com.example.shoppingTop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTvX4IHYdxVcI1u2V_5m-lHSqaE4R7-vY',
    appId: '1:247885656080:web:59abbd27901fe1f4ad1a95',
    messagingSenderId: '247885656080',
    projectId: 'doan-9657f',
    authDomain: 'doan-9657f.firebaseapp.com',
    storageBucket: 'doan-9657f.appspot.com',
    measurementId: 'G-YXW24C9QX2',
  );
}
